exclude: |
  (?x)(
    ^data/|
    ^tests/test_data/
  )
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0  # Use the ref you want to point at
    hooks:
    -   id: trailing-whitespace
    -   id: requirements-txt-fixer
    -   id: end-of-file-fixer
    -   id: debug-statements
    -   id: check-yaml
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-case-conflict
    -   id: check-ast
    -   id: check-added-large-files
        args: ['--maxkb=5120']
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
    -   id: isort
        args: ["--profile", "black"]
-   repo: https://github.com/ambv/black
    rev: 22.10.0
    hooks:
    -   id: black
        language_version: python3.10
