cnt_epochs: 20
uncase: False
batch_size: 48
max_length: 256
path_corpus: "/home/ra000012/data/NLP/corpora/shuffled/wiki_c4_256"
model_name: "./data/models/roberta-base"
# model_name: "prajjwal1/bert-mini"
test: False
precision: "FP32"
path_results: "/home/ra000012/data/NLP_outs"
create_unique_path: true
beta1: 0.9
beta2: 0.98
weight_decay: 0.01
initial_lr: 0.000001
max_lr: 0.0005
cnt_samples_per_epoch: 100000000
# cnt_samples_per_epoch: 200000
gradient_clip_val: 6.0
log_every_n_steps: 100
