cnt_epochs: 10  
uncase: False
batch_size: 32
max_length: 128
path_corpus: "./data/wikitext-2"
# path_corpus: "/groups2/gcb50300/data/NLP/corpora/CC-100/en"
name_model: "prajjwal1/bert-mini"
test: False
precision: "FP32"
path_results: "./logs"
create_unique_path: true
