path_corpus: "/mnt/storage/data/NLP/corpora/text8"
# path_corpus: "/home/blackbird/Projects_heavy/NLP/langmo/data/sense_small"
path_vocab: "/mnt/storage/data/NLP/vocabs/text8/m2/normal"
path_results: "./out/w2v"
batch_size: 256
embedding_size: 256
window_size: 2
cnt_epochs: 20
test: true
    