path_corpus: "/home/blackbird/Projects_heavy/NLP/langmo/data/wikitext-2"
# path_corpus: "/home/blackbird/Projects_heavy/NLP/langmo/data/sense_small"
path_vocab: "/mnt/storage/data/NLP/vocabs/bnc/m100"
path_results: "./out/w2v"
batch_size: 16
window_size: 2
cnt_epochs: 20
test: true
    