path_corpus: "/mnt/storage/data/NLP/corpora/brown/brown.txt"
#path_corpus: "/mnt/storage/data/NLP/corpora/text8/text8"
# path_corpus: "/home/blackbird/Projects_heavy/NLP/langmo/data/sense_small"
path_vocab: "/mnt/storage/data/NLP/vocabs/brown/m3"
path_results: "./out/w2v"
batch_size: 256
embedding_size: 128
window_size: 2
cnt_epochs: 10
test: false
    